version: "3.0"

services:

    agw_apitest:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        env_file:
            - .env
        environment:
            AGW_GATEWAYS_SEARCH_PATH: gateways/api_test
            MOCK_DP_ROUTES: mock/api_test.json
        ports:
            - 28199:8199 # nginx
            - 28171:8171 # gunicorn
        volumes:
            - ./agw:/app/agw
            - ./gateways:/app/gateways
            - ./mock:/app/mock

    apitest:
        build:
            context: ./
            dockerfile: ./tests/api/Dockerfile
        environment:
            AGW: ${AGW:-http://agw_apitest:8199}
        command: ["./extras/wait-for-it.sh", "agw_apitest:8199", "--strict", "--timeout=10", "--", "pytest", "-rfxXs", "./tests/api/tests"]
        depends_on:
            - agw_apitest
        volumes:
            - ./:/app
